services:
  web:
    image: "php:8.2-cli"
    ports:
      - "8000:8000"

    volumes:
      - .:/hemaScorecard

    command: >
      sh -c "apt-get update && apt-get install -y unzip git &&
             php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\" &&
             php composer-setup.php --install-dir=/usr/local/bin --filename=composer &&
             rm composer-setup.php &&
             composer install --working-dir=/hemaScorecard &&
             docker-php-ext-install mysqli &&
             docker-php-ext-enable mysqli &&
             pecl install xdebug-3.3.2 ||
             docker-php-ext-enable xdebug &&
             php -S 0.0.0.0:8000 -t /hemaScorecard"

    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    links:
      - db
  db:
    image: "mysql:5.7.33"
    ports:
      - "3306:3306"

    environment:
      MYSQL_DATABASE: ScorecardV5
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
      MYSQL_ROOT_PASSWORD: passw0rd

    volumes:
      - ./includes:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql